name = "book-stack"
# pages_build_output_dir = "dist"
compatibility_date = "2024-03-12"

# KV Cache for Book Stack
[[kv_namespaces]]
binding = "BOOK_STACK_CACHE"
id = "d55f8a31bbc6438dbe83742586f5c867"

# [[rate_limiting]]
# binding = "RATE_LIMITER"
# limit = 60
# period = 60
